### ISSUE TITLE
The manual not for psychics

### ISSUE THREAD

**Issue by NeilRiver** [Takaovi/SpotifyPatcher#1]
Hello dear author, I'm sorry, but I'm not a psychic and I don't know how to use your program. Can you write an instruction on what to do with this program and what advantages does it give?

**Comment by Takaovi** [comment]
[Use this link](https://github.com/Takaovi/SpotifyPatcher/releases/download/V1.0.1-beta/SpotifyPatcher.zip) to download the program. Unzip the downloaded file and run SpotifyPatcher.exe. Now patch all and it should do its job. If not then please inform me what happened.
