### ISSUE TITLE
disable auto update not working

### ISSUE THREAD

**Issue by spinalgr1990** [Takaovi/SpotifyPatcher#3]
disable auto update not working with version 1.1.62

**Comment by Takaovi** [comment]
Hello,

There is a reason why I've included an older version of Spotify with the program. I can't promise the functionality for new versions. 

Though, do remember to check that your Windows hosts file has all the [necessary blocks](https://github.com/Takaovi/SpotifyPatcher/blob/master/SpotifyPatcher/Resources/Batch/hosts). 

Thanks.

**Comment by spinalgr1990** [comment]
the only host that blocks autoupdate is

127.0.0.1 spclient.wg.spotify.com

but I can't play anything if I enable that host

**Comment by Takaovi** [comment]
Alright,

You need to use an older version of Spotify, such as the one provided, or it will not function properly.

Hopefully that works for you, and if not, I wish you good luck in finding another patcher. There are probably a ton out there.

Thanks.
