### ISSUE TITLE
Integrate that script

### ISSUE THREAD

**Issue by spinalgr1990** [Takaovi/SpotifyPatcher#4]
Integrate that script that disables auto update in the newer version

Open Admin Command Prompt and type

rm %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

This will not allow spotify to update

**Comment by brosaki** [comment]
"rm"?

**Comment by Takaovi** [comment]
What exactly would you like me to do? Add that to the NoUpdates.bat script?

This whole project's a mess tbh, many things don't do anything. (Such as that script mentioned) The only thing you need to stop ads and the update is a change of the hosts file and possibly downloading an older version of Spotify...

The idea of all these batch files and modifications was to throw shit at Spotify and just pray it would do something useful, lmao.

[This](https://github.com/Takaovi/ShutUpSpotify) does exactly the same job as this project, just without bullshit.
